import = ["/home/prajwal.adhikari@tekvortex.local/.config/alacritty/tokyonight/tokyonight_night.toml"]

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "Firacode NerdFont"
style = "Bold"

[font.italic]
family = "Firacode NerdFont"
style = "Italic"

[font.normal]
family = "Firacode NerdFont"
style = "Regular"

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
dynamic_title = false
opacity = 0.93

[window.dimensions]
columns = 125
lines = 30

# [window.padding]
# x = 5
# y = 5

